name: Bug report
description: Report a bug with Typedown. Please provide as much details as possible, including screenshots if necessary.
body:
  - type: markdown
    attributes:
      value: Thanks for filing an issue 😄 !
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open '…'
        2. Execute '…'
        3. Click on '…'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: How easily can you reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: input
    attributes:
      label: Typedown version
      placeholder: '0.2.0'
  - type: input
    attributes:
      label: Visual Studio Code version
      placeholder: 1.61.2
  - type: input
    attributes:
      label: Operating System version
      placeholder: macOS Big Sur 11.6
