name: integration

on: [push, pull_request]

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # Run on external PRs, but not on internal PRs as they'll be run by the push event to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
